services:
  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb
    restart: always
    ports:
      - "${MONGO_DB_PORT}:27017"
    environment:
      MONGODB_INITDB_ROOT_USERNAME: "${MONGO_DB_USERNAME}"
      MONGODB_INITDB_ROOT_PASSWORD: "${MONGO_DB_PASSWORD}"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
